
.PHONY: clean

clean:
find ./ -name "*.swp"|xargs rm
find ./ -name "*.swl"|xargs rm
find ./ -name "*.swn"|xargs rm
find ./ -name "*.swo"|xargs rm
find ./ -name "*.swm"|xargs rm
find ./ -name "*~"|xargs rm
